export const iconOptions = [
  { title: "Help Circle", value: "help-circle" },
  { title: "Book", value: "book" },
  { title: "File Question", value: "file-question" },
  { title: "Search", value: "search" },
  { title: "Scale", value: "scale" },
  { title: "Gavel", value: "gavel" },
  { title: "Files", value: "files" },
  { title: "Shield", value: "shield" },
  { title: "Users", value: "users" },
  { title: "Bookmark", value: "bookmark" },
  { title: "Building", value: "building" },
  { title: "Library", value: "library" },
  { title: "Star", value: "star" },
  { title: "Landmark", value: "landmark" },
  { title: "Scroll", value: "scroll" },
  { title: "Check Circle", value: "check-circle" },
  { title: "Alert Circle", value: "alert-circle" },
  { title: "Info", value: "info" },
  { title: "Lightbulb", value: "lightbulb" },
  { title: "Balance", value: "balance" },
  { title: "Calculator", value: "calculator" },
  { title: "Clock", value: "clock" },
  { title: "Dollar Sign", value: "dollar-sign" },
  { title: "Calendar", value: "calendar" },
];
